"""add mythic tables

Revision ID: 86981bc09690
Revises: be24780c0da0
Create Date: 2025-07-31 13:06:22.557573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86981bc09690'
down_revision = 'be24780c0da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_chain',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attack_step',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['attack_chain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('step_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['attack_step.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.add_column('user_account', sa.Column('username', sa.String(length=256), nullable=False))
    op.add_column('user_account', sa.Column('role', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_user_account_username'), 'user_account', ['username'], unique=True)
    op.create_unique_constraint(None, 'user_account', ['role'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_account', type_='unique')
    op.drop_index(op.f('ix_user_account_username'), table_name='user_account')
    op.drop_column('user_account', 'role')
    op.drop_column('user_account', 'username')
    op.drop_table('agent')
    op.drop_table('attack_step')
    op.drop_table('attack_chain')
    # ### end Alembic commands ###
